# Site settings
title: JNRPE
email: massimiliano.ziccardi@gmail.com
description: >
  This is the description of the JNRPE Site
baseurl: ""
url: "http://localhost:4001"
twitter_username: ziccardi
github_username: ziccardi
port: 4001

sass:
    sass_dir: _sass
include: ['_pages']

kramdown:
  input: GFM

markdown: kramdown
